### ISSUE TITLE
기능 요청: aws s3 버킷에 이미지 올리기

### ISSUE THREAD

**Issue by kwangyoulsagong** [ktb-23/healthkungya-backend#22]
## 기능 설명
사용자가 사진을 업로드하면, 이 사진은 AWS S3 버킷의 특정 이미지 폴더에 저장됩니다. 저장이 완료된 후, 사진의 링크가 생성되어 클라이언트에게 전달됩니다. 이 과정은 AWS와 연동하여 진행됩니다.

## 기대 효과
- 효율적인 이미지 저장 및 관리: AWS S3를 사용하여 이미지를 저장함으로써, 대용량의 이미지 파일을 안정적으로 저장하고 관리할 수 있습니다. 이는 서버의 스토리지 부담을 줄이고, 이미지 접근 속도를 향상시킬 수 있습니다
- 편리한 이미지 접근: 클라이언트는 업로드된 이미지에 대한 링크를 받아볼 수 있어, 해당 이미지를 쉽게 접근하고 사용할 수 있습니다. 이로 인해 사용자 경험이 향상됩니다.
- 확장성: AWS S3는 높은 확장성과 안정성을 제공하므로, 많은 수의 이미지 파일을 효율적으로 처리할 수 있습니다. 또한, 이미지 파일에 대한 요청 처리 속도도 향상됩니다.
- 자동화된 이미지 처리: 사진 업로드 및 링크 생성 과정이 자동화되므로, 사용자에게 빠르고 원활한 이미지 업로드 경험을 제공할 수 있습니다
## 추가 정보
기타 참고할 사항이 있다면 작성해주세요.

**Comment by PokingTeemo** [comment]
완료하였습니다!
